# Generated by Django 2.1.3 on 2019-05-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpreds',
            name='predCat',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
