# Generated by Django 2.1.3 on 2019-05-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_taskpreds_predcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskpreds',
            name='answer',
        ),
    ]
