# Generated by Django 2.1.3 on 2019-05-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_taskpreds_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpreds',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taskpreds',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
