# Generated by Django 2.1.3 on 2019-05-13 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190513_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpreds',
            name='recruit',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='taskpreds',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 13, 15, 10, 474989)),
        ),
    ]
